# Generated by Django 3.2 on 2023-03-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230303_0919'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personfilmwork',
            name='person_filmwork_idx',
        ),
        migrations.AlterUniqueTogether(
            name='personfilmwork',
            unique_together={('film_work', 'role', 'person')},
        ),
    ]
