# Generated by Django 3.2 on 2023-03-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_auto_20230301_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person",
                to="movies.person",
            ),
        ),
    ]
