# Generated by Django 3.2 on 2023-03-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_personfilmwork_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(related_name='genres', through='movies.GenreFilmwork', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(related_name='persons', through='movies.PersonFilmwork', to='movies.Person'),
        ),
    ]
