# Generated by Django 3.2 on 2023-03-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_auto_20230301_1715"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genrefilmwork",
            name="genre",
            field=models.ForeignKey(
                db_column="genre_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genres",
                to="movies.genre",
            ),
        ),
    ]
